#:schema node_modules/wrangler/config-schema.json
name = "svelte5-ecommerce"
compatibility_date = "2024-10-22"
main = ".svelte-kit/cloudflare/_worker.js"
assets = { directory = ".svelte-kit/cloudflare", binding = "ASSETS" }

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "svelte5-ecommerceDb"
database_id = "7839da2e-8ef5-46c1-94e6-fb111d636688"

[[r2_buckets]]
binding = 'BUCKET' # <~ valid JavaScript variable name
bucket_name = 'ecommerce-bucket'